### PR TITLE
Include `pop-hp-vendor` in pool on 22.04

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by jackpot51** [comment]
All its friends have to be included too:

- pop-hp-vendor-dkms
- pop-hp-wallpapers

**Comment by jackpot51** [comment]
The best way to test the pool for completeness is to build the ISO locally, run it in a VM, disable networking, then attempt to install pop-hp-vendor. If it complains about missing packages, those have to be added to the pool. You can quickly edit the pool by running `make clean-pool`

**Comment by ids1024** [comment]
Ah, adding a package to this list doesn't also add depends and recommends? Then yeah, a couple other things are needed.

**Comment by jackpot51** [comment]
Exactly, here we have to build the full list of packages that are needed.

**Comment by ids1024** [comment]
Had trouble building the ISO, but I got it working with `make GPG_NAME=...`. Seems to have everything it needs now.

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
I'm just gonna merge, I'm not sure what QA is really possible without building an ISO from this and then adding the distinst PR.

**Comment by leviport** [comment]
I was building one locally, but yeah that's probably way faster.

**Pull request merged**
